### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
title: Ozan Kiratli, PhD | Bioinformatician 
description: Personal website powered by Jekyll
baseurl: ""

# LANDING PAGE
username: Ozan Kiratli, PhD
typing_text: Bioinformatician
email: ozankiratli@protonmail.com
github_username: ozankiratli
codepen_username: 
dev_username: 
linkedin_username: ozankiratli
twitter_username: 
blog_link: https://ozankiratli.github.io/blog # Full link for the blog

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: About Me

# SKILLS SECTION
show_skills_card: true
skills_title: Skills

# TIMELINE SECTION
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: /files/Resume.pdf

# PROJECTS SECTION
show_projects_card: true
show_projects: false
projects_title: Projects
show_os_projects: true
os_projects_title: Github Projects

# CONTACT SECTION
show_contact_card: true
contact_title: Contact
contact_description: Feel free to contact me.

# GITHUB-METADATA
repository: ozankiratli/ozankiratli.github.io
projects:
  # sortby: pushed, stars 
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
     - ozankiratli.github.io
     - dotfiles
     - swayconfig
     - Template-Project
     - PiHole-BlockLists
     - NordVPNonOVPN
     - tuxisalive
     - Resume_CSS


# GOOGLE-ANALYTICS
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
    "vendor",
  ]
